version: 2

sources:
  - name: norm
    database: group5
    schema: norm
    tables:
     - name: t_city
     - name: t_country
     - name: t_customer
     - name: t_employee
     - name: t_order
     - name: t_order_line
     - name: t_region
     - name: t_return
     - name: t_segment
     - name: t_ship_mode
     - name: t_shipment
     - name: t_state
  - name: snapshots
    database: group5
    schema: snapshots
    tables:
     - name: sp_dim_customer
     - name: sp_dim_geography
     - name: sp_dim_employee
     - name: sp_dim_date
     - name: sp_fact_order
  - name: public
    database: group5
    schema: public
    tables:
     - name: dim_date



models:
  - name: dim_customer
    columns:
      - name: sk_customer
        description: "A unique identifier for the customer"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "The id of the customer"
      - name: customer_name
        description: "The name of the customer"
      - name: segment
        description: "The segment of the customer"
      - name: valid_from
        description: "The date on which this customer data started to be valid"
      - name: valid_to
        description: "The date on which this customer data expired"
      - name: created_at
        description: "The date this data was created"
      - name: last_updated_at
        description: "The date this data was last updated"
  
  - name: dim_geography
    columns:
      - name: sk_geography
        description: "A unique identifier for the geography"
        tests:
          - unique
          - not_null
      - name: city
      - name: state
      - name: region
      - name: country
      - name: valid_from
        description: "The date on which this customer data started to be valid"
      - name: valid_to
        description: "The date on which this customer data expired"
      - name: created_at
        description: "The date this data was created"
      - name: last_updated_at
        description: "The date this data was last updated"
  
  - name: dim_employee
    columns:
      - name: sk_employee
        description: "A unique identifier for the employee"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "The id of the employee"
      - name: employee_name
        description: "The name of the employee"
      - name: valid_from
        description: "The date on which this customer data started to be valid"
      - name: valid_to
        description: "The date on which this customer data expired"
      - name: created_at
        description: "The date this data was created"
      - name: last_updated_at
        description: "The date this data was last updated"

  - name: dim_date
    columns:
      - name: sk_date
        description: "A unique identifier for the date"
        tests:
          - unique
          - not_null
      - name: date
      - name: day
      - name: month
      - name: year
      - name: month_name
      - name: month_name_short
      - name: week_number
      - name: day_of_week
      - name: day_of_week_name
      - name: quarter
      - name: is_weekend